version: '3.8'
services:
  frontend:
    build: ./frontend
    environment:
      - VITE_REACT_APP_API_URL=http://localhost:8000
    ports:
      - 8080:80
  api:
    build: ./api
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      SECRET_KEY: your_secret # change here
      PSQL_CONN_STRING: postgresql://cards:cards@db/cards
    volumes:
      - ./static:/static
  socket:
    build: ./socket
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      SECRET_KEY: your_secret # change here
      PSQL_CONN_STRING: postgresql://cards:cards@db/cards
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: cards
      POSTGRES_PASSWORD: cards
      POSTGRES_DB: cards
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always