version: '3'
services:
  api:
    build: ./api
    ports:
      - 9000:8000
    environment:
      SECRET_KEY: your_secret
      PSQL_CONN_STRIN: postgresql://postgres_user:posgres_password@db/postgres_db
    volues:
      - ./statis:/static
  frontend:
    build: ./frontend
    ports:
      - 9001:80
  socket:
    build: ./socket
    ports:
      - 9002:3000
    environment:
      SECRET_KEY: your_secret
      PSQL_CONN_STRIN: postgresql://postgres_user:posgres_password@db/postgres_db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: posgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql